// Authored product content. No executable engine callbacks occur in this data.
export const ACTS = [
  "The Return",
  "The Bell Keeps Count",
  "The Living Witness",
  "The Count Room",
  "The Last Bell",
];
export const ITEMS = {
  cassette: {
    name: "Elian’s cassette",
    text: "Two bells after a gull cry. “The sea is the long breathing. If I answer with your name, it is not me.” The leader bears your sister’s handwriting.",
  },
  key: {
    name: "Intake key",
    text: "An iron key stamped VISITOR. The reverse is deliberately blank.",
  },
  lantern: {
    name: "Service lantern",
    text: "A cold lantern from the market. Its empty reservoir takes the resin treatment described at the apothecary.",
  },
  resin: {
    name: "Tested resin",
    text: "The blue-sealed mixture burns without smoke. Combine it with the service lantern.",
  },
  protectedLantern: {
    name: "Treated lantern",
    text: "A steady amber flame. It slows exposure in the lower passages; it cannot make a voice truthful.",
  },
  register: {
    name: "First Register",
    text: "Two independent records verify June Arlen, Tomas Reed, Ada Wren and Niko Bell. Chosen aliases remain beside their names.",
  },
  archive: {
    name: "Original shutoff order",
    text: "At 02:13 the oxygen supply was isolated. The signature and carbon impression match. This is physical evidence, not a voice.",
  },
  relay: {
    name: "Relay contract",
    text: "Orison Recovery will carry the acoustic signal through municipal infrastructure. A transmission channel can also carry recorded testimony.",
  },
  chalk: {
    name: "Survey chalk",
    text: "Waterproof chalk supplied with a return-route diagram. Leave marks at physical junctions; do not follow voices.",
  },
  core: {
    name: "Bell Core",
    text: "The portable resonator contains a pattern formed from the erased records. It is a vessel, not another child.",
  },
};
export const ENDINGS = {
  witness: {
    title: "THE WITNESS",
    subtitle: "A record belongs to everyone.",
    text: "You send the shutoff order, the relay contract and eight verified names through the town’s public line. You leave each chosen alias beside the name an institution gave it. The bell tries to add a thirteenth child. You identify the vessel instead. With the truth held in many places, it no longer needs one body to carry it. At the road, the sea makes an ordinary sound. You do not ask it to carry another name.",
  },
  silence: {
    title: "THE SILENCE",
    subtitle: "An ending is not an erasure.",
    text: "Outer, inner, outer. The final brace breaks beneath your hand. The voices are allowed to stop. No new name replaces them. Saint Orison loses its impossible rooms, but the papers you carry do not prove everything that happened here. You leave the unproven spaces blank. This time, a blank is an admission of what you do not know—not an instruction to forget.",
  },
  vessel: {
    title: "THE OFFERED NAME",
    subtitle: "A burden has changed hands.",
    text: "You give the machine your own copied pattern. The town grows quiet, and the others can leave, but the bell still has a container. A person at the gate recognizes your face. Your name will not stay with them. You do not ask remembrance as payment. Behind you, a new line appears in the visitor ledger. Its ink is still wet.",
  },
};
const object = (id, name, kind, text, extra = {}) => ({
  id,
  name,
  kind,
  text,
  ...extra,
});
const puzzle = (title, question, options, answer, success, wrong, hints) => ({
  title,
  question,
  options,
  answer,
  success,
  wrong,
  hints,
});
export const ROOMS = [
  {
    id: "town-gate",
    name: "Town Gate",
    act: 0,
    minutes: 8,
    theme: "gate",
    tint: "#547f83",
    accent: "#dfac67",
    weather: "rain",
    pressure: 150,
    subtitle: "The road ends. The invitation does not.",
    arrival:
      "Salt gathers on the envelope in your coat. Elian’s cassette arrived yesterday, though she has been missing for eleven days. Ahead, the gatehouse light moves across an empty crossing. Beyond it stands the hospital’s bell tower. You are Mara Venn. You came to find your sister, not to give this place another name.",
    goal: "Read the crossing notice, then open a safe route into town.",
    warning:
      "The indicator turns amber. A second bell is gathering in the iron.",
    critical: "A figure stands inside the fog. The shelter is still open.",
    retreat:
      "You step behind the stone recess. Something crosses where you were standing. It never enters the marked shelter.",
    objects: [
      object(
        "notice",
        "Crossing notice",
        "inspect",
        "WAIT THROUGH TWO BELLS. CROSS ON THE DARK LAMP. Under the official lettering, someone has scratched: Do not answer the visitor intercom with a name. You copy the warning exactly.",
        { clue: "crossing-rule" },
      ),
      object(
        "callbox",
        "Visitor intercom",
        "inspect",
        "“Visitor?” The voice is yours, with an old childhood hesitation. Three photograph badges hang below: red anchor, white fern, black gull. The fourth roster line has no photograph. A blank record is different from an offered name.",
        { clue: "blank-record" },
      ),
      object(
        "latch",
        "Gatehouse roster",
        "puzzle",
        "A mechanical selector waits beneath the roster. Its empty line is a real selectable entry, not a missing label.",
      ),
      object(
        "marks",
        "Maintenance recess",
        "optional",
        "Inside the dependable shelter, arrows cut into the stone lead toward an unlit service passage. Their white ends point back to the road. You record the return direction.",
        { flag: "gateMarks" },
      ),
    ],
    puzzle: puzzle(
      "The visitor register",
      "What will you submit to the intercom?",
      ["Mara Venn", "Elian Venn", "The blank record"],
      [2],
      "The printer produces a blank visitor pass and an intake key. “Present,” says the intercom. You have opened a route without offering a living identity.",
      "The speaker repeats the offered name. You withdraw the selector before confirming. The blank row remains available.",
      [
        "The warning says not to offer a name.",
        "A record can be empty without being absent.",
        "Submit the blank record.",
      ],
    ),
    required: ["crossing-rule", "blank-record"],
    reward: "key",
    choices: [
      {
        id: "shelter",
        label: "Wait in shelter; cross on the dark lamp",
        text: "You wait through both bells. When the lamp dies, you cross without looking toward the footsteps.",
      },
      {
        id: "passage",
        label: "Take the marked maintenance passage",
        text: "You follow the carved arrow through the gatehouse wall. A second arrow marks a return route.",
        flag: "gateMarks",
      },
    ],
  },
  {
    id: "visitor-centre",
    name: "Visitor Centre",
    act: 0,
    minutes: 10,
    theme: "office",
    tint: "#6c7970",
    accent: "#b6bd85",
    pressure: 155,
    subtitle: "Someone kept the lights on for you.",
    arrival:
      "The visitor centre smells of warm paper. Every chair faces the illuminated town map. An evacuation notice has yesterday’s date, but the visitor book was signed this morning. Elian has drawn a small wave beside her entry. She did not leave by the road.",
    goal: "Restore the map and establish Elian’s next stop.",
    warning: "The first bank of fluorescent tubes goes dark.",
    critical:
      "The announcement loses its words. Only the shape of your name remains.",
    retreat:
      "The service cabinet has a manual isolation switch. You turn it off and wait in the daylight panel by the door.",
    objects: [
      object(
        "diagram",
        "Circuit diagram",
        "inspect",
        "The map transformer is isolated from the building supply. The diagram reads: disconnect RED, connect BLUE, then connect AMBER. The small circuit powers only the map. You will not touch the building mains.",
        { clue: "map-circuit" },
      ),
      object(
        "book",
        "Visitor book",
        "inspect",
        "ELIAN VENN — CAFÉ, 07:10. Her note reads: “They sent everyone home except the people who remembered.” Beneath it, the clerk has stamped TRANSFERRED instead of DEPARTED.",
        { clue: "cafe-lead" },
      ),
      object(
        "cabinet",
        "Map service cabinet",
        "puzzle",
        "Three low-voltage toggles sit inside an insulated enclosure. Their symbols match the circuit diagram.",
      ),
      object(
        "staff",
        "Staff evacuation list",
        "optional",
        "Two columns share the same names: DEPARTED and RETAINED. The carbon sheet reveals a deliberate change, not a clerical error. You photograph both layers.",
        { flag: "selectiveEvacuation" },
      ),
    ],
    puzzle: puzzle(
      "Bring the map online",
      "Operate the circuit in the documented order.",
      ["Disconnect red", "Connect blue", "Connect amber"],
      [0, 1, 2],
      "The map lights in sections. A chalk line links the Café, market and bell tower. Beside the hospital, an underground route has been rubbed out.",
      "The safety breaker opens. No fuse is consumed. Re-read the diagram and reset the sequence.",
      [
        "Use the cabinet’s diagram, not the announcement.",
        "Isolate before reconnecting.",
        "Red off, blue on, amber on.",
      ],
    ),
    required: ["map-circuit", "cafe-lead"],
    choices: [
      {
        id: "front",
        label: "Follow Elian’s café entry",
        text: "You take the street named in the visitor book.",
      },
      {
        id: "service",
        label: "Follow the evacuation staff route",
        text: "The route passes the same café, behind its delivery door. The evacuation list stays with your evidence.",
        flag: "selectiveEvacuation",
      },
    ],
  },
  {
    id: "closed-cafe",
    name: "Closed Café",
    act: 0,
    minutes: 12,
    theme: "cafe",
    tint: "#746954",
    accent: "#efb875",
    pressure: 160,
    subtitle: "Her voice remembers the wrong things.",
    arrival:
      "Two cups stand beneath a dead wall clock. One holds a skin of milk; the other is dry. From the kitchen, Elian asks you to come closer. On your cassette she warned you about a voice that knows names. You put the tape on the counter before answering anything.",
    goal: "Compare the radio signal with Elian’s original cassette.",
    warning: "The kitchen voice moves closer without crossing the doorway.",
    critical: "Every empty table seems to have a breath beneath it.",
    retreat:
      "You step outside the service door. The kitchen voice keeps talking to an empty café.",
    objects: [
      object(
        "tape",
        "Cassette comparison",
        "inspect",
        "On the original tape a gull cries, then two low tide bells sound. Elian says, “The long breathing.” The kitchen voice says, “The hungry sea.” It knows her tone, not her private phrase.",
        { clue: "true-signal" },
      ),
      object(
        "receipt",
        "Counter receipt",
        "inspect",
        "A service receipt shows three radio channels: 81 — inland dispatch; 94 — tide station; 107 — hospital relay. Someone circled the tide station and wrote TWO AFTER THE GULL.",
        { clue: "radio-channels" },
      ),
      object(
        "radio",
        "Shortwave radio",
        "puzzle",
        "The dial is worn at three frequencies. A small speaker can play the signal without you speaking into the room.",
      ),
      object(
        "kitchen",
        "Kitchen recorder",
        "optional",
        "From the threshold you see a loop of tape feeding through a recorder. Its power cable runs into a municipal junction, not a wall socket. You photograph the connection without entering.",
        { flag: "relayEvidence" },
      ),
    ],
    puzzle: puzzle(
      "A voice and a recording",
      "Select the channel matching the original signal.",
      ["81 · inland dispatch", "94 · tide station", "107 · hospital relay"],
      [1],
      "The gull cries, followed by two bells. Under the noise, Elian says, “Follow the service lanterns. Do not let them tell you I was taken. I chose to interrupt the relay.”",
      "The voice is convincing, but its signal does not match your cassette. You switch it off.",
      [
        "The tape contains a tide signal.",
        "The receipt identifies the station.",
        "Tune to 94.",
      ],
    ),
    required: ["true-signal", "radio-channels"],
    choices: [
      {
        id: "record",
        label: "Keep the recording and leave",
        text: "You preserve the message. Elian entered voluntarily; whatever comes next must respect that.",
      },
      {
        id: "trace",
        label: "Trace the cable from the threshold",
        text: "The cable joins the market’s service trunk. You record its route.",
        flag: "relayEvidence",
      },
    ],
  },
  {
    id: "market-street",
    name: "Market Street",
    act: 1,
    minutes: 10,
    theme: "market",
    tint: "#536968",
    accent: "#c68658",
    pressure: 145,
    subtitle: "The town closes one shutter at a time.",
    arrival:
      "Rain drums on canvas roofs. An abandoned freight lantern lies beside a half-lowered shutter. The café’s cable disappears through a service trunk on the far side. This crossing can be left safe for someone returning behind you.",
    goal: "Secure the shutter and collect a service lantern.",
    warning: "A shutter slams at the far end of the market.",
    critical: "The counterweight begins to slip; the open crossing narrows.",
    retreat:
      "You withdraw to the freight alcove, beyond the shutter’s travel. Its safety stop catches.",
    objects: [
      object(
        "plate",
        "Freight safety plate",
        "inspect",
        "PIN THE WEIGHT. RAISE THE SHUTTER. ENGAGE THE CATCH. The plate shows a raised shutter held by the catch, never by a person beneath it.",
        { clue: "shutter-order" },
      ),
      object(
        "lamp",
        "Abandoned service lantern",
        "collect",
        "The lantern is cold but intact. A paper tie reads: “Apothecary resin only. Smoke carries the echo.” You put it in your satchel.",
        { item: "lantern" },
      ),
      object(
        "winch",
        "Shutter winch",
        "puzzle",
        "The winch has a weight pin, a winding handle and a locking catch. All three are within reach from the safe side.",
      ),
      object(
        "stall",
        "Repair stall",
        "optional",
        "A bent return-route sign lies beneath a tarpaulin. You straighten it and point it toward the safe freight alcove. Somebody following you will not have to guess.",
        { flag: "marketSafe" },
      ),
    ],
    puzzle: puzzle(
      "Keep a way open",
      "Secure the crossing using the safety procedure.",
      ["Pin the counterweight", "Raise the shutter", "Engage the catch"],
      [0, 1, 2],
      "The catch locks with a clear metallic click. The crossing remains open without your weight on the handle.",
      "The handle stops against its interlock. You remain on the safe side. Start with the counterweight.",
      [
        "The plate gives the procedure.",
        "Secure the weight before moving the shutter.",
        "Pin, raise, engage.",
      ],
    ),
    required: ["shutter-order"],
    requiredItem: "lantern",
    choices: [
      {
        id: "direct",
        label: "Cross through the freight opening",
        text: "The lantern knocks softly against your satchel.",
      },
      {
        id: "secure",
        label: "Secure a return marker before crossing",
        text: "You tie a pale marker at the opening. The route will be recognizable even without the lamps.",
        flag: "marketSafe",
      },
    ],
  },
  {
    id: "apothecary",
    name: "Apothecary",
    act: 1,
    minutes: 12,
    theme: "apothecary",
    tint: "#466b60",
    accent: "#b6c98a",
    pressure: 155,
    subtitle: "A steady flame is not a promise.",
    arrival:
      "Bottles crowd the window, turning streetlight green. The dispensing bench holds three samples and an intact test lamp. A handwritten warning separates two ideas: a flame can protect your breathing, but it cannot protect your judgment.",
    goal: "Test the resin, then prepare the lantern.",
    warning: "Smoke gathers in the doorway although nothing is burning there.",
    critical: "The back-room glass darkens from the inside.",
    retreat:
      "You close the fire screen and return to the ventilated dispensing window.",
    objects: [
      object(
        "recipe",
        "Resin preparation",
        "inspect",
        "The treatment must burn amber, leave no black residue and keep the test strip dry. Red seal: black soot. Green seal: wet strip. Blue seal: clear glass and a dry strip. These observations are written beside the used samples.",
        { clue: "resin-test" },
      ),
      object(
        "note",
        "Keeper’s note",
        "inspect",
        "“Do not trust a voice because your lamp stays lit. The resin limits the acoustic dust; it does not turn a copy into a person.” At the bottom Elian has written: “Ask what I called the sea.”",
        { clue: "lantern-limits" },
      ),
      object(
        "bench",
        "Sample bench",
        "puzzle",
        "Each sample has a used test strip and a differently shaped seal. The blue seal is triangular, the red round, the green square.",
      ),
      object(
        "drawer",
        "Dispensing drawer",
        "optional",
        "A clinical note states that the affected patients were deprived of oxygen before any supernatural event was recorded. Someone tried to make the phenomenon an alibi.",
        { flag: "clinicalEvidence" },
      ),
    ],
    puzzle: puzzle(
      "Choose the tested treatment",
      "Which sample passes all three observations?",
      [
        "Round red seal · soot",
        "Square green seal · damp",
        "Triangular blue seal · dry",
      ],
      [2],
      "You bottle the blue-sealed resin. Open your satchel and combine it with the service lantern. The result will slow exposure below the town.",
      "This sample failed its recorded test. You leave it sealed and do not waste the service lantern.",
      [
        "All three conditions must pass.",
        "Reject soot and moisture.",
        "Choose the triangular blue seal.",
      ],
    ),
    required: ["resin-test", "lantern-limits"],
    reward: "resin",
    requiredExitItem: "protectedLantern",
    choices: [
      {
        id: "street",
        label: "Carry the treated lantern to the tower",
        text: "The flame burns steadily. You remember what it cannot promise.",
      },
      {
        id: "clinical",
        label: "Take the clinical note as well",
        text: "You preserve the note that separates the human crime from the phenomenon.",
        flag: "clinicalEvidence",
      },
    ],
  },
  {
    id: "bell-tower-base",
    name: "Bell Tower Base",
    act: 1,
    minutes: 13,
    theme: "tower",
    tint: "#68635d",
    accent: "#deab6d",
    pressure: 140,
    subtitle: "A machine made to sound like mercy.",
    arrival:
      "A huge shaft turns above the maintenance platform. Each revolution pulls a cable into the hospital below. The governor can delay one cycle without breaking the transmission line. A crowbar offers a faster, permanent silence for this local mechanism.",
    goal: "Learn the bell cycle and choose how to interrupt it.",
    warning: "The governor’s amber mark approaches the contact plate.",
    critical: "The platform shivers. The next ring is almost engaged.",
    retreat:
      "You step off the marked platform and pull its emergency guard closed.",
    objects: [
      object(
        "log",
        "Governor service log",
        "inspect",
        "For a non-destructive delay: open BYPASS, release TENSION, engage BRAKE. The relay stays connected. A warning below says breaking the shaft severs the public transmission route.",
        { clue: "governor-order" },
      ),
      object(
        "stair",
        "Acoustic brace diagram",
        "inspect",
        "The three resonant braces are struck OUTER, INNER, OUTER to fracture an isolated core. Disconnect the relay before attempting it. You copy the diagram; this could end the vessel without replacing its occupant.",
        { clue: "silence-method" },
      ),
      object(
        "governor",
        "Governor controls",
        "puzzle",
        "Three hand controls correspond to the service log. A fourth, red-painted shaft can be broken only after an explicit choice.",
      ),
      object(
        "relay",
        "Relay junction",
        "optional",
        "The connection label identifies an outgoing municipal channel. You photograph its configuration; the same line could carry evidence instead of the bell.",
        { flag: "relayEvidence" },
      ),
    ],
    puzzle: puzzle(
      "Delay the ring",
      "Operate the non-destructive governor procedure.",
      ["Open bypass", "Release tension", "Engage brake"],
      [0, 1, 2],
      "The governor settles. One cycle has been delayed, and the relay remains intact. You can keep this arrangement or choose the destructive shortcut before leaving.",
      "The safety gate closes over the controls. You release them and return to the documented starting position.",
      [
        "The service log describes a delay, not a demolition.",
        "Bypass before tension.",
        "Bypass, tension, brake.",
      ],
    ),
    required: ["governor-order", "silence-method"],
    choices: [
      {
        id: "preserve",
        label: "Leave the relay intact",
        text: "You preserve the channel. The later Witness transmission remains possible.",
        flag: "relayIntact",
      },
      {
        id: "break",
        label: "Break the shaft · disables Witness transmission",
        text: "You strike the red shaft. The outgoing relay snaps. The Silence and Vessel methods remain possible; public transmission through this line does not.",
        flag: "relayBroken",
      },
    ],
  },
  {
    id: "school-hall",
    name: "School Hall",
    act: 2,
    minutes: 13,
    theme: "school",
    tint: "#68726e",
    accent: "#b9b697",
    pressure: 165,
    subtitle: "Twelve desks. An empty place.",
    arrival:
      "The schoolroom belongs to the old hospital estate. Twelve desks face a slate board; a thirteenth position has no desk. In the glass you see a child turning a page. When you turn, only the page has moved. June speaks from the reflection: “Say what you can prove.”",
    goal: "Cross-check four identities without erasing chosen aliases.",
    warning: "Chalk taps the same number against every desk.",
    critical: "The slate begins to write your childhood name.",
    retreat:
      "You turn the slate face down and stand beside the open corridor door.",
    objects: [
      object(
        "photos",
        "School photographs",
        "inspect",
        "Two independent records agree: anchor — June Arlen; fern — Tomas Reed; gull — Ada Wren; wave — Niko Bell. The photograph captions and signed letters match. Some later aliases were chosen by the children to protect one another.",
        { clue: "names-first-four" },
      ),
      object(
        "lesson",
        "June’s slate",
        "inspect",
        "“We traded names so none of us would be taken alone.” The slate asks for the photograph order: anchor, fern, gull, wave. You will keep the aliases beside the verified records rather than replacing them.",
        { clue: "school-order" },
      ),
      object(
        "register",
        "Class register",
        "puzzle",
        "Four symbol slots await the verified names. The empty place is labelled HOLDING PATTERN in an adult hand.",
      ),
      object(
        "reflection",
        "Speak to June",
        "optional",
        "Mara: “I will leave the name you chose beside the one they wrote.” June: “Then you have learned more than the teacher.” Her reflection closes the book. You do not ask her to perform another answer.",
        { flag: "consent" },
      ),
    ],
    puzzle: puzzle(
      "Keep both records",
      "Match anchor, fern, gull and wave in order.",
      ["June Arlen", "Tomas Reed", "Ada Wren", "Niko Bell"],
      [0, 1, 2, 3],
      "The First Register opens. Four identities are cross-checked, and their chosen aliases remain intact. The thirteenth position records an apparatus, not a thirteenth child.",
      "The two records disagree with that placement. Nothing is overwritten. Compare the photograph captions again.",
      [
        "Use both the photographs and letters.",
        "The order is anchor, fern, gull, wave.",
        "June, Tomas, Ada, Niko.",
      ],
    ),
    required: ["names-first-four", "school-order"],
    reward: "register",
    choices: [
      {
        id: "copy",
        label: "Copy the records with aliases intact",
        text: "You preserve the distinction between verified history and chosen identity.",
      },
      {
        id: "ask",
        label: "Ask June what should remain private",
        text: "June leaves one margin closed. You carry the proof without claiming every memory.",
        flag: "consent",
      },
    ],
  },
  {
    id: "flooded-archive",
    name: "Flooded Archive",
    act: 2,
    minutes: 17,
    theme: "archive",
    tint: "#48717c",
    accent: "#9cb7a7",
    pressure: 135,
    subtitle: "The truth has a waterline.",
    arrival:
      "Water presses paper against the lower shelves. The index desk is raised above the flood. A pump can expose the correct aisle briefly, but searching every cabinet would lose the record you actually need. You begin with the index, not the water.",
    goal: "Recover the shutoff record and its carbon original.",
    warning: "Water reaches the first red mark on the shelf legs.",
    critical: "The far shelf tilts. The raised exit is still clear.",
    retreat:
      "You return to the raised index desk. The pump’s reserve tank drains the nearest aisle; essential records remain in their protective cases.",
    objects: [
      object(
        "index",
        "Archive index",
        "inspect",
        "The card reads: CLINICAL → OXYGEN → 02:13. The carbon original is stored separately in a waterproof case. The official ledger calls the deaths a fever event; the equipment order records a deliberate shutoff.",
        { clue: "archive-index" },
      ),
      object(
        "pump",
        "Pump instructions",
        "inspect",
        "The pump must discharge toward the street drain, not the records sump. Its hand control grants one safe crossing. The raised walkway remains available if the water returns.",
        { clue: "archive-safe" },
      ),
      object(
        "cabinet",
        "Indexed records cabinet",
        "puzzle",
        "Three selector wheels search department, equipment and recorded time. You can operate them from the raised walkway.",
      ),
      object(
        "carbon",
        "Waterproof carbon case",
        "optional",
        "The carbon impression matches the signed order. You lift the case by its tether rather than crossing the unstable far shelf. The original will let others inspect the proof for themselves.",
        { item: "archive", flag: "originalSaved", requiresSolved: true },
      ),
    ],
    puzzle: puzzle(
      "Find the actual order",
      "Select the indexed department, equipment and time.",
      ["Clinical", "Oxygen", "02:13", "Admissions", "Bell repairs"],
      [0, 1, 2],
      "The protective drawer opens. At 02:13 the oxygen supply was shut off by order, not accident. You photograph the record. The tethered carbon case can now be recovered as stronger public proof.",
      "The index does not reference that combination. The drawer stays sealed and the record remains safe.",
      [
        "Start from the index desk.",
        "Three fields identify the record.",
        "Clinical, Oxygen, 02:13.",
      ],
    ),
    required: ["archive-index", "archive-safe"],
    choices: [
      {
        id: "photo",
        label: "Leave with the photographed record",
        text: "You leave with the records you gathered. Any original proof already recovered remains protected in your satchel.",
      },
      {
        id: "original",
        label: "Recover the tethered carbon original",
        text: "You bring out the waterproof case. Public evidence need not depend on your testimony alone.",
        item: "archive",
        flag: "originalSaved",
      },
    ],
  },
  {
    id: "chapel-nave",
    name: "Chapel Nave",
    act: 2,
    minutes: 15,
    theme: "chapel",
    tint: "#665c72",
    accent: "#d9ba7b",
    pressure: 180,
    subtitle: "A confession is not a repair.",
    arrival:
      "Father Vale waits beside a closed side chapel. He says Elian is safe because she is contained. Her voice arrives through a hospital intercom behind him: “Ask me something he did not teach me.” The private phrase on your cassette offers a better test than the face in the dark.",
    goal: "Verify Elian’s identity and decide whether to release her.",
    warning:
      "The intercom begins replacing pauses with another speaker’s breath.",
    critical:
      "Vale reaches for the isolation switch. You can still stop the conversation.",
    retreat:
      "You switch to the local line and close the public microphone. Elian waits without repeating your name.",
    objects: [
      object(
        "confession",
        "Vale’s confession",
        "inspect",
        "“We called it mercy because we were afraid to call it theft.” Vale’s signed statement names Silas as the architect of the holding pattern. It also admits that restoring a record is not permission to use its subject.",
        { clue: "vessel-truth" },
      ),
      object(
        "line",
        "Private archive line",
        "inspect",
        "Elian: “I came willingly to stop the relay. They closed the isolation door after me. The Thirteenth is made from what they erased. It is not another child.” Mara: “And the sea?” Elian waits for you to choose the answer from the original tape.",
        { clue: "elian-location" },
      ),
      object(
        "intercom",
        "Verify the private phrase",
        "puzzle",
        "Use the cassette’s private phrase before deciding about the isolation door. Elian is physically in the annex beyond the side chapel.",
      ),
      object(
        "promise",
        "Listen without bargaining",
        "optional",
        "Elian: “Do not make saving me the price of believing me.” Mara: “You can come with me, or keep the archive line open. I will tell you what each choice means.”",
        { flag: "elianTrust" },
      ),
    ],
    puzzle: puzzle(
      "The living witness",
      "What did Elian call the sea?",
      ["The hungry sea", "The long breathing", "The last choir"],
      [1],
      "Elian adds the second half without prompting: “And you called it a place to hide.” The live pulse meter agrees with the private line. You can release her into the marked stair or keep the archive channel open with her consent.",
      "The copied public voice answers first. You close that channel. The original cassette remains a trustworthy reference.",
      [
        "Recall the original cassette, not the kitchen.",
        "The phrase describes a breath.",
        "The long breathing.",
      ],
    ),
    required: ["vessel-truth", "elian-location"],
    choices: [
      {
        id: "release",
        label: "Release Elian into the marked stair",
        text: "You open the isolation door. Elian steps onto the physical stair beside you. She will travel with you through the parish house and tunnels.",
        flag: "elianReleased",
      },
      {
        id: "line",
        label: "Ask Elian to maintain the archive line",
        text: "Elian agrees to remain at its protected station. She will speak through the line; she will not appear physically beside you.",
        flag: "elianRemote",
      },
    ],
  },
  {
    id: "parish-house",
    name: "Parish House",
    act: 3,
    minutes: 12,
    theme: "house",
    tint: "#735e53",
    accent: "#e2b781",
    pressure: 165,
    subtitle: "Someone ate breakfast above all of this.",
    arrival:
      "A cup has left a pale ring on Silas’s writing desk. Beyond the domestic rooms, a utility door leads toward the count chamber. Three photographs show the same study as its window is bricked, its cabinet moved and its bell painted. The ordinary changes hide an ordinary safe.",
    goal: "Recover the relay contract and the descent equipment.",
    warning: "Footsteps stop outside the study whenever you stop reading.",
    critical: "The handle turns once, although the stair is empty.",
    retreat:
      "You move into the utility vestibule and secure its mechanical bolt.",
    objects: [
      object(
        "photos",
        "Three dated photographs",
        "inspect",
        "The photographs show three changes in order. Four window panels were bricked; the ledger cabinet moved to alcove one; seven bands were painted on the bell. A note says the safe code follows these repairs: 4, 1, 7.",
        { clue: "safe-code" },
      ),
      object(
        "letter",
        "Elian’s letter",
        "inspect",
        "“Mara, I blamed you for burning Father’s papers. Now I know he asked you to. That does not make it harmless. It means we both need a record that survives what we want to believe.” You leave the original folded along its old creases.",
        { clue: "family-history" },
      ),
      object(
        "safe",
        "Silas’s wall safe",
        "puzzle",
        "The safe has a mechanical number wheel. Its combination is established by changes in the room, not a hidden random code.",
      ),
      object(
        "chalk",
        "Survey equipment",
        "collect",
        "A bundle of waterproof chalk sits beside a descent diagram. The keeper marked return directions before entering the tunnels. You take the remaining chalk.",
        { item: "chalk" },
      ),
    ],
    puzzle: puzzle(
      "A domestic combination",
      "Enter the repair counts in chronological order.",
      ["4", "1", "7", "2", "8"],
      [0, 1, 2],
      "Inside lies the Orison Recovery relay contract and a utility pass. The company plans to carry the holding pattern through the town’s infrastructure. The same channel can transmit public evidence.",
      "The wheel returns to its stop. The photographs still show all three numbers.",
      [
        "Read the changes in chronological order.",
        "Windows, cabinet alcove, painted bands.",
        "4, 1, 7.",
      ],
    ),
    required: ["safe-code", "family-history"],
    reward: "relay",
    requiredItem: "chalk",
    choices: [
      {
        id: "utility",
        label: "Descend by the documented utility stair",
        text: "You carry the contract and a practical route back.",
      },
      {
        id: "letter",
        label: "Discuss the letter before descending",
        text: "You admit what you burned. Elian does not forgive on command, but she hears the admission.",
        flag: "elianTrust",
      },
    ],
  },
  {
    id: "maintenance-tunnels",
    name: "Maintenance Tunnels",
    act: 3,
    minutes: 15,
    theme: "tunnels",
    tint: "#47646b",
    accent: "#bd9d70",
    pressure: 125,
    subtitle: "Follow the pipes. Let the voices get lost.",
    arrival:
      "The treated lantern warms the first junction. Physical pipes continue through the walls even when the sounds suggest another corridor. A survey plate describes the safe utility route. You can mark the return before the town changes around it.",
    goal: "Follow the utility markings and preserve a return route.",
    warning: "The voice behind you takes the sound of your own footsteps.",
    critical: "The far light dies. Your chalk marks remain visible.",
    retreat:
      "You return to the pump niche using the pipes you can touch. The voice keeps walking beyond it.",
    objects: [
      object(
        "plate",
        "Utility route plate",
        "inspect",
        "Safe survey order: OPEN EYE, MOUTH, CLOSED EYE, EMPTY CIRCLE. The symbols mean observe, refuse the invitation, ignore the lure, leave an unclaimed place. Their shapes are embossed as well as painted.",
        { clue: "tunnel-order" },
      ),
      object(
        "window",
        "Observation window",
        "inspect",
        "Below the glass, acoustic tubes end in empty masks. Recorded names feed a single resonator. There are twelve patient channels and one container. The machinery confirms what Elian said: the Thirteenth is not a person to recover.",
        { clue: "container-proof" },
      ),
      object(
        "junction",
        "Junction selectors",
        "puzzle",
        "Four pipe gates carry the embossed survey symbols. The service plan defines their safe order.",
      ),
      object(
        "mark",
        "Mark the return route",
        "use",
        "The raised stone beside the junction is dry enough for waterproof survey chalk. A clear return arrow will survive the lanterns.",
        { use: "chalk", flag: "returnMarked" },
      ),
    ],
    puzzle: puzzle(
      "A route that can be checked",
      "Follow the physical survey order.",
      ["Open eye", "Mouth", "Closed eye", "Empty circle"],
      [0, 1, 2, 3],
      "The gates open toward the count chamber. You can trace the route by its continuous pipes; the disembodied directions fall silent.",
      "That gate loops back to the same marked junction. No equipment is lost. Use the embossed survey plate.",
      [
        "The plate is a physical record.",
        "Observe, refuse, ignore, leave empty.",
        "Open eye, mouth, closed eye, empty circle.",
      ],
    ),
    required: ["tunnel-order", "container-proof"],
    choices: [
      {
        id: "direct",
        label: "Continue along the verified pipes",
        text: "You remember the pipe route, but leave no extra marker.",
      },
      {
        id: "mark",
        label: "Chalk the return direction before proceeding",
        text: "A white arrow points back to the pump niche. The later ascent will have a reliable landmark.",
        flag: "returnMarked",
      },
    ],
  },
  {
    id: "well-chamber",
    name: "Well Chamber",
    act: 3,
    minutes: 18,
    theme: "well",
    tint: "#476d70",
    accent: "#d8ae64",
    pressure: 180,
    subtitle: "Nothing down here is asking to be useful.",
    arrival:
      "The shaft is wider than the chapel above. Twelve acoustic lines terminate around a portable core. Four further identities are preserved in paired admission and family records: Iris Cole, Samir Hale, Ruth Fen and Leon March. With the First Register, eight can be verified. The empty thirteenth channel is the vessel.",
    goal: "Recover the Bell Core and choose a fully explained intervention.",
    warning:
      "The core begins repeating the first syllable of every recorded name.",
    critical:
      "The outgoing relay pulses. An intervention is still yours to choose.",
    retreat:
      "You close the core’s acoustic shutter. It cannot take an offered name through a closed channel.",
    objects: [
      object(
        "names",
        "Paired identity records",
        "inspect",
        "Iris Cole, Samir Hale, Ruth Fen and Leon March each appear in an admission record and a signed family record. Their aliases are retained. These four join the four from the school register. You will not invent the remaining names.",
        { clue: "names-second-four" },
      ),
      object(
        "methods",
        "Intervention instructions",
        "inspect",
        "WITNESS: intact relay, First Register, original shutoff order, relay contract, eight verified names. SILENCE: isolate relay, strike braces outer–inner–outer; no replacement. VESSEL: explicitly offer your own copied pattern; others leave, the burden continues. Every method needs the core released first.",
        { clue: "ending-methods" },
      ),
      object(
        "core",
        "Core release collars",
        "puzzle",
        "The plate on the core reads: CLOSE SHUTTER, ISOLATE FEED, RELEASE COLLARS. This removes the resonator safely without yet choosing its fate.",
      ),
      object(
        "voices",
        "Listen to the unclaimed silence",
        "optional",
        "Mara: “You do not have to answer.” Some lines carry a breath. Others carry nothing. You leave their record open rather than filling it with what you hope to hear.",
        { flag: "consent" },
      ),
    ],
    puzzle: puzzle(
      "Release the resonator",
      "Follow the core’s isolation plate.",
      ["Close shutter", "Isolate feed", "Release collars"],
      [0, 1, 2],
      "The Bell Core comes free. Eight identities are verified. Choose an intervention with its stated requirements and consequence. Nothing is committed until you confirm.",
      "A mechanical interlock holds. The core remains seated. Begin by closing the acoustic shutter.",
      [
        "The isolation plate gives a safe order.",
        "Close the acoustic path before releasing hardware.",
        "Shutter, feed, collars.",
      ],
    ),
    required: ["names-second-four", "ending-methods"],
    reward: "core",
    choices: [
      {
        id: "witness",
        label: "WITNESS · transmit names and original proof",
        text: "You preserve the original records and open the verified public channel. The vessel will lose its role as the sole container.",
        ending: "witness",
      },
      {
        id: "silence",
        label: "SILENCE · isolate and end the vessel",
        text: "You disconnect the relay and strike outer, inner, outer. No new person is offered. Public proof remains limited to what you carry.",
        ending: "silence",
      },
      {
        id: "vessel",
        label: "VESSEL · knowingly offer your own pattern",
        text: "You offer your own copied childhood pattern. The others can leave; you accept a continuing burden and the loss of being reliably remembered.",
        ending: "vessel",
      },
    ],
  },
  {
    id: "return-ascent",
    name: "Return Ascent",
    act: 4,
    minutes: 12,
    theme: "tunnels",
    tint: "#5b625f",
    accent: "#d5a574",
    pressure: 115,
    subtitle: "The way back remembers your hands.",
    arrival:
      "The pipes have stopped singing together. Some lights are gone, but the material route still exists. What you repaired, marked or broke now matters. Elian is beside you only if you opened the isolation door; otherwise the archive line speaks from fixed emergency stations.",
    goal: "Use the verified return route and make it back above ground.",
    warning: "Water strikes the pump housing from the wrong side.",
    critical: "The upper service gate begins to settle into its frame.",
    retreat:
      "You shelter in the pump niche. Its mechanical hand release still works after the bell’s intervention.",
    objects: [
      object(
        "route",
        "Return survey plate",
        "inspect",
        "The reverse-route instruction reads: EMPTY CIRCLE, CLOSED EYE, MOUTH, OPEN EYE. Even if you left no chalk, the embossed symbols remain. Familiar voices are not a substitute for a physical route.",
        { clue: "return-order" },
      ),
      object(
        "station",
        "Emergency line",
        "inspect",
        "Elian: “I can follow the same physical route. Tell me the symbols, not what the voices say.” You explain each junction. If she stayed at the archive station, this line is her way toward the protected upper stair.",
        { clue: "elian-return" },
      ),
      object(
        "gates",
        "Return gates",
        "puzzle",
        "The selectors open the route in reverse. Their raised symbols can be checked by the lantern or by touch.",
      ),
      object(
        "assist",
        "Keep the emergency line open",
        "optional",
        "You hold the local relay long enough for Elian to repeat the return instructions. She chooses her own pace. Helping does not erase the records already secured in your satchel.",
        { flag: "elianHelped" },
      ),
    ],
    puzzle: puzzle(
      "Reverse the survey",
      "Choose the reverse of the descent route.",
      ["Open eye", "Mouth", "Closed eye", "Empty circle"],
      [3, 2, 1, 0],
      "The upper gate releases. You reach the parish stair with the core’s consequence behind you and your evidence still accounted for.",
      "The selected passage returns to the pump niche. The raised reverse-route plate remains readable.",
      [
        "The return plate reverses the descent.",
        "Begin at the empty circle.",
        "Empty circle, closed eye, mouth, open eye.",
      ],
    ),
    required: ["return-order", "elian-return"],
    choices: [
      {
        id: "leave",
        label: "Continue to the square",
        text: "You take the upper stair. Elian’s route follows the instructions you gave.",
      },
      {
        id: "help",
        label: "Hold the line until Elian confirms her route",
        text: "“Open eye,” she says at the last junction. This time the answer comes from a person who can leave.",
        flag: "elianHelped",
      },
    ],
  },
  {
    id: "town-square",
    name: "Town Square",
    act: 4,
    minutes: 8,
    theme: "square",
    tint: "#758887",
    accent: "#e0c196",
    pressure: 0,
    subtitle: "Morning is not an acquittal.",
    arrival:
      "The town square is quiet enough to hear the sea. A few residents wait beside the public notice stand. They ask what happened beneath their homes. You have knowledge, physical evidence and gaps. None of those should be disguised as another.",
    goal: "Choose how to share the record without claiming what you cannot prove.",
    warning: "",
    critical: "",
    retreat:
      "You sit on the dry edge of the fountain and let the quiet remain quiet.",
    objects: [
      object(
        "board",
        "Public notice stand",
        "inspect",
        "The evacuation notice calls the hospital incident a structural failure. There is room beside it for a record that can be inspected, challenged and kept by more than one person.",
        { clue: "public-record" },
      ),
      object(
        "satchel",
        "Review the evidence",
        "inspect",
        "You separate what you witnessed, what was independently recorded, what Elian told you and what remains unknown. The distinction belongs in the public account.",
        { clue: "evidence-boundary" },
      ),
      object(
        "account",
        "Prepare your account",
        "puzzle",
        "The residents are listening. You can give them a truthful account without turning uncertainty into a performance.",
      ),
      object(
        "vale",
        "Father Vale at the fountain",
        "optional",
        "Vale: “Will they forgive us?” Mara: “That is not a task I can complete for you.” You leave him with his signed confession and a choice to repeat it publicly.",
        { flag: "valeAccountable" },
      ),
    ],
    puzzle: puzzle(
      "What can be said",
      "Choose the statement supported by your records.",
      [
        "I can prove every voice was truthful",
        "Here is the proof, testimony and what remains unknown",
        "Nothing happened here",
      ],
      [1],
      "You lay out the records and label their limits. The residents can keep copies. No single person has to become the town’s memory again.",
      "That would replace one convenient story with another. You return to the evidence and its limits.",
      [
        "Separate proof from testimony.",
        "Unknowns belong in an honest account.",
        "Offer proof, testimony and the remaining unknowns.",
      ],
    ),
    required: ["public-record", "evidence-boundary"],
    choices: [
      {
        id: "copies",
        label: "Leave copies with the residents",
        text: "The record begins to exist in more than one place.",
        flag: "publicCopies",
      },
      {
        id: "originals",
        label: "Arrange independent custody of the originals",
        text: "You identify which papers are originals and which are copies. The residents choose separate custodians.",
        flag: "publicCopies",
      },
    ],
  },
  {
    id: "exit-road",
    name: "Exit Road",
    act: 4,
    minutes: 5,
    theme: "gate",
    tint: "#889895",
    accent: "#e6cea1",
    pressure: 0,
    subtitle: "You can leave a place without finishing its grief.",
    arrival:
      "The gatehouse fan turns in the morning air. The fourth roster line is still blank unless you offered your pattern below. You stop where the cassette first played. The sea sounds larger now that nothing is trying to speak over it.",
    goal: "Acknowledge the consequence and decide what you carry home.",
    warning: "",
    critical: "",
    retreat: "For once there is no pressure to move.",
    objects: [
      object(
        "cassette",
        "The original cassette",
        "inspect",
        "Elian: “The long breathing.” You let the recording reach its ordinary click at the end. An old message does not need to answer a new question.",
        { clue: "last-listen" },
      ),
      object(
        "road",
        "Look back at Saint Orison",
        "inspect",
        "The tower is a structure again. Some windows are broken, some are lit, and people will have to decide what to do with both. Your intervention changed the town. It did not replace the work of living in it.",
        { clue: "last-look" },
      ),
      object(
        "letter",
        "Write the first line home",
        "puzzle",
        "A blank page rests against your satchel. You can begin without pretending the account is complete.",
      ),
      object(
        "elian",
        "Wait for Elian",
        "optional",
        "You leave space beside you without calling a name into the gate. What she remembers depends on your intervention. What you owe her does not.",
        { flag: "elianHelped" },
      ),
    ],
    puzzle: puzzle(
      "The first line",
      "How will your account begin?",
      [
        "Everything is fixed",
        "This is what I can tell you",
        "There is nothing to remember",
      ],
      [1],
      "You write one honest sentence. The road ahead is ordinary, and that is enough to begin.",
      "The sentence closes a question you have not answered. You turn to a clean line.",
      [
        "The whole story does not have to fit one sentence.",
        "Leave room for what remains unknown.",
        "This is what I can tell you.",
      ],
    ),
    required: ["last-listen", "last-look"],
    choices: [
      {
        id: "home",
        label: "Leave Saint Orison",
        text: "You walk toward the sea road with the record and its consequences.",
      },
      {
        id: "stay",
        label: "Stay until the record is safely copied",
        text: "You delay your departure for an ordinary responsibility: ensuring the papers can outlast you.",
        flag: "publicCopies",
      },
    ],
  },
];
export const ROOM_BY_ID = Object.fromEntries(ROOMS.map((r) => [r.id, r]));
export const CONTENT_VERSION = "orison-campaign/1";
