import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
export const root = resolve(fileURLToPath(new URL("../..", import.meta.url)));
const read = (p) => JSON.parse(readFileSync(resolve(root, p), "utf8"));
export function assembleContent() {
  const campaign = read("content/progression/campaign.json"),
    packages = {};
  const rooms = campaign.locations.map((id) => {
    const base = "src/kits/locations/" + id;
    const c = Object.fromEntries(
      [
        "location",
        "objects",
        "investigations",
        "puzzles",
        "dialogue",
        "observations",
        "choices",
        "pressure",
        "presentation",
      ].map((k) => [k, read(base + "/content/" + k + ".json")]),
    );
    const sequences = Object.fromEntries(
      ["entry", "investigations", "exit", "recovery"].map((k) => [
        k,
        read(base + "/sequences/" + k + ".json"),
      ]),
    );
    const assets = read(base + "/assets/manifest.json"),
      bindings = read(base + "/assets/bindings.json");
    if (c.location.id !== id || !c.investigations.length)
      throw new Error("Incomplete location " + id);
    const primary = c.investigations[0],
      puzzle = c.puzzles.find((p) => p.id === primary.puzzleId);
    if (!puzzle) throw new Error("Unknown puzzle " + id);
    const { id: puzzleId, ...legacyPuzzle } = puzzle;
    const objects = c.objects.map((o) => {
      const observation = c.observations.find((x) => x.id === o.id);
      if (!observation)
        throw new Error("Missing observation " + id + "." + o.id);
      return { ...o, text: observation.text };
    });
    packages[id] = { content: c, sequences, assets, bindings };
    return {
      ...c.location,
      ...c.presentation,
      ...c.pressure,
      arrival: c.dialogue.arrival,
      objects,
      puzzle: legacyPuzzle,
      choices: c.choices,
      required: primary.required,
    };
  });
  return {
    ACTS: campaign.acts,
    CONTENT_VERSION: campaign.version,
    ITEMS: read("content/shared/items.json"),
    ENDINGS: read("content/progression/ending-rules.json"),
    RECIPES: read("content/shared/recipes.json"),
    ROOMS: rooms,
    LOCATION_PACKAGES: packages,
  };
}
export function buildContent({ check = false } = {}) {
  const c = assembleContent();
  const output =
    "// GENERATED by tools/authoring/build-content.mjs. Edit location packages and shared JSON.\n" +
    Object.entries(c)
      .map(
        ([k, v]) =>
          "export const " + k + " = " + JSON.stringify(v, null, 2) + ";",
      )
      .join("\n") +
    "\nexport const ROOM_BY_ID=Object.fromEntries(ROOMS.map(r=>[r.id,r]));\n";
  const path = resolve(root, "content/campaign.js");
  if (check) {
    if (readFileSync(path, "utf8") !== output)
      throw new Error("Generated content is stale. Run npm run content:build.");
  } else writeFileSync(path, output);
  return { locations: c.ROOMS.length };
}
if (process.argv[1] === fileURLToPath(import.meta.url))
  console.log(buildContent({ check: process.argv.includes("--check") }));
